import {describe,it,expect} from 'vitest';
import {fixture,sourceBundle,sourceObservation,quality,buildRun,authorize,send} from './engine';
describe('Data COUNTS synthetic rehearsal',()=>{
 it('exports FHIR-shaped source evidence with preserved codes, values and subject links',()=>{const l=fixture(true)[0]!;const source=sourceObservation(l);expect(source.valueQuantity.value).toBe(l.value);expect(source.code.coding[0]!.code).toBe(l.code);expect(source.subject.reference).toBe('Patient/SYN-001');expect(sourceBundle(true).entry).toHaveLength(156);});
 it('reports both seeded defects and blocks output',async()=>{const r=await buildRun(false,false);expect(quality(fixture())).toHaveLength(2);expect(r.output).toHaveLength(0);expect(()=>authorize(r,false,false)).toThrow();});
 it('preserves codes and units, reconciles disjoint exclusions, and shifts temporal intervals',async()=>{const r=await buildRun(true,false);expect(r.sourceCount).toBe(144);expect(r.output).toHaveLength(120);expect(r.cohortExcluded).toBe(12);expect(r.permissionExcluded).toBe(12);const source=fixture(true)[0]!;const out=r.output[0]!;expect(out.code).toBe(source.code);expect(out.unit).toBe(source.unit);expect(Date.parse(out.issued)-Date.parse(out.effectiveDateTime)).toBe(Date.parse(source.issued)-Date.parse(source.effectiveDateTime));expect(out).not.toHaveProperty('patient');});
 it('reproduces package identity and logical output',async()=>{expect(await buildRun(true,false)).toEqual(await buildRun(true,false));});
 it('invalidates approval when permissions change and excludes subsequent rows',async()=>{const r=await buildRun(true,false);expect(()=>send(r,r.digest,true,true,[])).toThrow('Inputs changed');const next=await buildRun(true,true);expect(next.output).toHaveLength(108);expect(next.output.some(l=>l.patientToken==='DEMO-TOKEN-003')).toBe(false);expect(next.digest).not.toBe(r.digest);});
 it('prevents unapproved send and duplicate ingestion after timeout',async()=>{const r=await buildRun(true,false);expect(()=>send(r,null,true,false,[])).toThrow();const receipts=send(r,r.digest,true,false,[]);expect(send(r,r.digest,true,false,receipts)).toHaveLength(1);expect(receipts[0]!.status).toBe('awaiting');});
});
