import {expect,it} from 'vitest';
import {buildRun,hashValue} from './engine';
import {planRefresh,applyRefresh} from './refresh';
async function setup(){const run=await buildRun(true,false),base={digest:'review-a',rows:run.output};const rows=structuredClone(base.rows.slice(1));rows[0]!.value=1.25;rows.push({...base.rows[0]!,id:'late-arrival'});return {base,target:{digest:'review-b',rows}};}
it('reproduces exact target from additions, updates and withdrawals, then safely reruns',async()=>{const {base,target}=await setup();const plan=await planRefresh(base,target);expect(plan.upserts.map(c=>c.kind)).toEqual(['updated','added']);expect(plan.withdrawals).toHaveLength(1);const first=await applyRefresh(base,plan);expect(first.snapshot).toEqual(target);expect(first.status).toBe('applied');expect((await applyRefresh(first.snapshot,plan)).status).toBe('already-applied');expect(base.rows).toHaveLength(120);});
it('rejects wrong baseline, tampering and incomplete target without modifying source',async()=>{const {base,target}=await setup(),plan=await planRefresh(base,target),original=structuredClone(base);await expect(applyRefresh({...base,digest:'other'},plan)).rejects.toThrow('baseline');plan.upserts[0]!.record.value=999;await expect(applyRefresh(base,plan)).rejects.toThrow('integrity');const {planDigest:_,...bad}=plan;await expect(applyRefresh(base,{...bad,planDigest:await hashValue(bad)})).rejects.toThrow('reconcile');expect(base).toEqual(original);});
it('does not infer a merge from a changed patient token',async()=>{const {base,target}=await setup();target.rows[0]!.patientToken='different';await expect(planRefresh(base,target)).rejects.toThrow('Authoritative identity review');});
it('preserves target record order and deterministic plan identity',async()=>{const {base}=await setup(),target={digest:'reorder',rows:[...base.rows].reverse()};const a=await planRefresh(base,target),b=await planRefresh(base,target);expect(a.planDigest).toBe(b.planDigest);expect(a.upserts).toEqual([]);expect((await applyRefresh(base,a)).snapshot).toEqual(target);});

it('rejects one review identity for different snapshots and duplicate record IDs',async()=>{const {base,target}=await setup();await expect(planRefresh(base,{...target,digest:base.digest})).rejects.toThrow('One review identity');await expect(planRefresh(base,{...target,rows:[...target.rows,target.rows[0]!]})).rejects.toThrow('unique');});
it('rejects conflicting operations and incomplete inventory even with recomputed plan hashes',async()=>{const {base,target}=await setup(),plan=await planRefresh(base,target);const resign=async(p:typeof plan)=>{const {planDigest:_,...content}=p;return {...content,planDigest:await hashValue(content)};};await expect(applyRefresh(base,await resign({...plan,upserts:[...plan.upserts,plan.upserts[0]!]}))).rejects.toThrow('operation');await expect(applyRefresh(base,await resign({...plan,targetOrder:plan.targetOrder.slice(1)}))).rejects.toThrow('inventory');});

it('rejects rehashed plans that reuse or omit target review identity',async()=>{const {base,target}=await setup(),plan=await planRefresh(base,target);for(const targetReviewDigest of [base.digest,'']){const {planDigest:_,...content}={...plan,targetReviewDigest};await expect(applyRefresh(base,{...content,planDigest:await hashValue(content)})).rejects.toThrow(/identit/);}});
