import type {DataCountsTab} from './navigation';
export type Requirement={id:number;name:string;status:'Partial'|'Simulated'|'Unverified';complexity:'High'|'Very high';existing:string;remaining:string;evidence:string;owner:string;destination:DataCountsTab};
export const requirements:Requirement[]=[
 {id:1,name:'Independent hospital operation',status:'Partial',complexity:'Very high',existing:'Desktop alpha and setup guidance.',remaining:'Hospital source connectors, VM deployment, immutable provenance, training, updates and free partner-use terms.',evidence:'Approved source extract and independent site-operated installation and recovery.',owner:'Hospital IT and source-system owners',destination:'System'},
 {id:2,name:'Authorized data requests',status:'Partial',complexity:'High',existing:'Versioned synthetic request and imported specification checker.',remaining:'Trusted approval, live availability, cohort execution, cadence and reproducible reruns.',evidence:'Authorized request executed against source, with every output bound to its request version.',owner:'Program and site data governance',destination:'Request'},
 {id:3,name:'Data quality',status:'Partial',complexity:'High',existing:'Laboratory completeness, duplicates, types and date checks.',remaining:'Representative domain-wide checks and validation; report anomalies before correction.',evidence:'Known-error extracts detected without modifying original values.',owner:'Clinical informatics and engineering',destination:'Issues'},
 {id:4,name:'De-identification',status:'Simulated',complexity:'Very high',existing:'Illustrative date shifting only.',remaining:'Validate the RFI de-identification pathway, identifiers and consistent patient date shifts.',evidence:'Privacy-approved specification, leakage tests and preserved temporal order.',owner:'Site privacy and clinical governance',destination:'Release & delivery'},
 {id:5,name:'Privacy-preserving linkage',status:'Simulated',complexity:'Very high',existing:'DEMO token fixtures.',remaining:'Approved site-local PPRL and consistent irreversible cross-site tokens.',evidence:'Cross-site validation and site approval before first live transmission.',owner:'Approved PPRL provider and sites',destination:'Release & delivery'},
 {id:6,name:'Source fidelity',status:'Partial',complexity:'High',existing:'Source locations, hashes and retained evidence.',remaining:'Lossless provenance, permission and ontology fields across sources; trace authorized changes only.',evidence:'Field-level source/output comparison with no invented mappings.',owner:'Source owners and clinical informatics',destination:'Source records'},
 {id:7,name:'Eligibility and revocation',status:'Simulated',complexity:'Very high',existing:'Synthetic permission exclusions.',remaining:'Authoritative eligibility, permission versions and subsequent refresh revocations.',evidence:'Cohort versus permission exclusions reconciled; revoked records absent from refreshes.',owner:'Hospital permission authority',destination:'Request'},
 {id:8,name:'Full and incremental refresh',status:'Partial',complexity:'Very high',existing:'Synthetic lifecycle and package identity.',remaining:'Production adds, updates, deletes, merges, unmerges, corrections and late arrivals.',evidence:'Idempotent refresh tests with stable tokens and distinct snapshot IDs.',owner:'Source integration and engineering',destination:'Activity'},
 {id:9,name:'Processing integrity',status:'Partial',complexity:'High',existing:'Six-stage local count reconciliation, full-source digest, synthetic journal and historical receipt recovery.',remaining:'Complete stage audit, count reconciliation and failure recovery for actual processing.',evidence:'Incomplete or failed stages block transmission; every stage has batch, count and outcome.',owner:'Engineering and site operations',destination:'Activity'},
 {id:10,name:'Security compliance posture',status:'Unverified',complexity:'Very high',existing:'Selected technical safeguards.',remaining:'Organizational ability to attest as a Business Associate to HIPAA Security Rule compliance.',evidence:'Reviewed risk assessment, policies, operational controls and supporting evidence.',owner:'Security and compliance leadership',destination:'System'},
 {id:11,name:'Protected security logging',status:'Partial',complexity:'High',existing:'Local audit foundations.',remaining:'Continuous protected SIEM-compatible authentication, admin, config and security events.',evidence:'Site identities, timestamps, resources and outcomes; tamper/deletion protection tested.',owner:'Site security and engineering',destination:'Activity'},
 {id:12,name:'Encryption and network restrictions',status:'Partial',complexity:'High',existing:'Renderer/filesystem restrictions; local JWE encrypted demo export and recovery.',remaining:'Managed site/recipient keys, enforced encrypted output and VM, required TLS, minimal services and approved outbound path. Plaintext internal review remains available.',evidence:'Encryption/recovery and deployment network tests, including setup provisioning.',owner:'Site infrastructure and security',destination:'System'},
 {id:13,name:'Hospital trust boundary',status:'Partial',complexity:'Very high',existing:'Local parsing and inference architecture.',remaining:'Validated site VM and IAM, no contractor remote management, de-identified tokenized output only.',evidence:'Site-controlled deployment and access review; outbound payload inspection.',owner:'Hospital IT and security',destination:'System'},
 {id:14,name:'Performance at scale',status:'Unverified',complexity:'High',existing:'Small synthetic tests and hardware checks.',remaining:'Representative baseline, 2x and 5x workloads, timings, throughput, resources and staffing.',evidence:'Repeatable workload reports on the target site hardware.',owner:'Engineering and site operations',destination:'Model setup'},
 {id:15,name:'Trusted broker delivery',status:'Simulated',complexity:'Very high',existing:'Local delivery and lost-receipt simulator.',remaining:'Actual broker package/schema, authenticated transport, reconciliation, retries and errors.',evidence:'Accepted test packages and duplicate-safe recovery from lost acknowledgments.',owner:'Program broker and integration team',destination:'Release & delivery'},
];
