import {validInstant} from '../data-counts/engine';
export type WireResponse={status:number;body:string;contentType?:string|null;contentLocation?:string|null;retryAfter?:string|null};
export type Transport=(url:string,options:{authenticate:boolean;bulk:boolean;signal?:AbortSignal})=>Promise<WireResponse>;
export type RawArtifact={label:string;body:string;sha256:string};
export type SourcePreview={sourceId:string;format:'FHIR R4'|'HL7 v2'|'Tabular';records:Record<string,unknown>[];artifacts:RawArtifact[];warnings:string[];complete:true;transactionTime?:string};
const MAX_BYTES=12*1024*1024,MAX_RECORDS=10000;
export async function hashText(text:string){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text))),b=>b.toString(16).padStart(2,'0')).join('');}
export function approvedUrl(raw:string,base?:string){const u=base?new URL(raw,base):new URL(raw);if(u.protocol!=='https:'||u.username||u.password||u.hash)throw Error('Use HTTPS without embedded credentials or fragments.');if(base&&u.origin!==new URL(base).origin)throw Error('Cross-origin source URL requires an approved hospital route or managed extract.');return u.href;}
export function fhirBase(raw:string){const u=new URL(approvedUrl(raw.trim()));if(u.search)throw Error('FHIR base must not contain query parameters.');return u.href.replace(/\/$/,'');}
function object(value:unknown):Record<string,any>{if(!value||typeof value!=='object'||Array.isArray(value))throw Error('Expected a source JSON object.');return value as Record<string,any>;}
function parse(body:string){try{return object(JSON.parse(body.replace(/^\uFEFF/,'')));}catch{throw Error('Source returned invalid JSON. No partial preview was accepted.');}}
function check(signal?:AbortSignal){if(signal?.aborted)throw Error('Preview cancelled. No partial result was accepted.');}
function resource(value:unknown){const r=object(value);if(typeof r.resourceType!=='string'||typeof r.id!=='string'||!r.id)throw Error('A source resource is missing its type or ID.');if(r.resourceType==='OperationOutcome')throw Error('Source reported an OperationOutcome. Resolve it before accepting this extract.');return r;}
function collect(){let bytes=0;const artifacts:RawArtifact[]=[],records:Record<string,unknown>[]=[],ids=new Set<string>();return {artifacts,records,async add(label:string,body:string){bytes+=new TextEncoder().encode(body).length;if(bytes>MAX_BYTES)throw Error('Preview exceeds 12 MiB. Use a smaller approved cohort.');artifacts.push({label,body,sha256:await hashText(body)});},push(r:Record<string,unknown>){const id=`${r.resourceType}/${r.id}`;if(ids.has(id))throw Error(`Duplicate resource identity ${r.resourceType}. Reconcile the source before accepting this preview.`);ids.add(id);records.push(r);if(records.length>MAX_RECORDS)throw Error('Preview exceeds 10,000 resources. Use a smaller approved cohort.');}};}
export function inspectCapabilities(body:string){const c=parse(body);if(c.resourceType!=='CapabilityStatement'||c.status!=='active'||c.kind!=='instance'||typeof c.fhirVersion!=='string'||!c.fhirVersion.startsWith('4.0.'))throw Error('This connector requires an active FHIR R4 (4.0.x) instance CapabilityStatement.');const server=(c.rest??[]).filter((r:any)=>r.mode==='server');const resources:{type:string;read:boolean;search:boolean}[]=server.flatMap((r:any)=>r.resource??[]).map((r:any)=>({type:String(r.type),read:(r.interaction??[]).some((x:any)=>x.code==='read'),search:(r.interaction??[]).some((x:any)=>x.code==='search-type')}));const groupExport=server.some((r:any)=>(r.resource??[]).some((x:any)=>x.type==='Group'&&(x.operation??[]).some((o:any)=>o.name==='$export'||o.name==='export')));return {version:c.fhirVersion as string,software:typeof c.software?.name==='string'?c.software.name:'Not supplied',resources,groupExport};}
export async function fetchPatientPreview(base:string,patients:string[],reports:boolean,transport:Transport,authenticate:boolean,signal?:AbortSignal):Promise<SourcePreview>{
 base=fhirBase(base);if(!patients.length||patients.length>10||new Set(patients).size!==patients.length||patients.some(p=>!/^[A-Za-z0-9.-]{1,64}$/.test(p)))throw Error('Enter 1–10 distinct FHIR patient IDs, using letters, digits, dots or hyphens.');
 const out=collect();
 for(const patient of patients){check(signal);const patientResponse=await transport(`${base}/Patient/${patient}`,{authenticate,bulk:false,signal});if(patientResponse.status!==200)throw Error('Patient read did not complete.');await out.add(`Patient read ${out.artifacts.length+1}`,patientResponse.body);const p=resource(parse(patientResponse.body));if(p.resourceType!=='Patient'||p.id!==patient)throw Error('Source returned a different patient identity.');out.push(p);
 for(const type of reports?['Observation','DiagnosticReport']:['Observation']){
 let next:string|undefined=`${base}/${type}?${new URLSearchParams({patient,_count:'100'})}`;const visited=new Set<string>();let matched=0,total:number|undefined;
 while(next){check(signal);if(visited.has(next)||visited.size>=25)throw Error('Source pagination repeated or exceeded 25 pages. No partial preview was accepted.');visited.add(next);const pageUrl:string=next;const response=await transport(pageUrl,{authenticate,bulk:false,signal});if(response.status!==200)throw Error('Source search did not complete.');await out.add(`${type} page ${visited.size}`,response.body);const bundle=parse(response.body);if(bundle.resourceType!=='Bundle'||bundle.type!=='searchset'||(bundle.entry!==undefined&&!Array.isArray(bundle.entry)))throw Error('Expected a complete FHIR searchset Bundle.');if(bundle.total!==undefined){if(!Number.isSafeInteger(bundle.total)||bundle.total<0||(total!==undefined&&total!==bundle.total))throw Error('Search count changed during pagination. Repeat the preview.');total=bundle.total;}
 for(const e of bundle.entry??[]){if(e.search?.mode&&e.search.mode!=='match')throw Error('Unexpected included/outcome resource. The preview requires an exact patient search.');const r=resource(e.resource);if(r.resourceType!==type)throw Error('Source search returned an unexpected resource type.');const reference=r.subject?.reference;if(reference!==`Patient/${patient}`&&reference!==`${base}/Patient/${patient}`)throw Error('Source resource does not reference the requested patient.');out.push(r);matched++;}
 const links=bundle.link??[];if(!Array.isArray(links))throw Error('Invalid pagination links.');const candidates=links.filter((l:any)=>l.relation==='next');if(candidates.length>1)throw Error('Ambiguous pagination links.');next=candidates.length?approvedUrl(String(candidates[0].url),pageUrl):undefined;
 }
 if(total!==undefined&&matched!==total)throw Error('Source search counts did not reconcile. No partial preview was accepted.');
 }}check(signal);return {sourceId:base,format:'FHIR R4',records:out.records,artifacts:out.artifacts,warnings:['Patient-scoped source preview only. Cohort and permission authorization remain separate.','Original resources retained; no terminology mapping or clinical inference performed.'],complete:true};
}
export async function fetchBulkPreview(base:string,group:string,since:string,transport:Transport,authenticate:boolean,signal?:AbortSignal,onProgress?:(message:string)=>void):Promise<SourcePreview>{
 base=fhirBase(base);if(!/^[A-Za-z0-9.-]{1,64}$/.test(group))throw Error('Enter the hospital-approved FHIR Group ID.');if(since&&!validInstant(since))throw Error('Incremental start must be an ISO timestamp with a timezone.');
 const types=['Patient','Observation','DiagnosticReport'];const q=new URLSearchParams({_type:types.join(',')});if(since)q.set('_since',since);
 const kickoff=`${base}/Group/${group}/$export?${q}`;const start=await transport(kickoff,{authenticate,bulk:true,signal});if(start.status!==202||!start.contentLocation)throw Error('Server did not accept an asynchronous Group export. Verify enabled Bulk Data support.');const polling=approvedUrl(start.contentLocation,kickoff);let response:WireResponse|undefined;
 for(let attempt=0;attempt<30;attempt++){check(signal);onProgress?.(`Waiting for hospital export · check ${attempt+1} of 30`);const retry=attempt?response?.retryAfter:start.retryAfter;const requested=retry?(/^\d+$/.test(retry)?Number(retry):Math.ceil((Date.parse(retry)-Date.now())/1000)):2;const delay=Number.isFinite(requested)?Math.max(0,requested):2;if(delay>30)throw Error('Server requested a longer wait. Preview stopped without polling early; contact hospital IT before starting another export job.');if(delay)await new Promise<void>(resolve=>{const stop=()=>{clearTimeout(timer);resolve();};const timer=setTimeout(()=>{signal?.removeEventListener('abort',stop);resolve();},delay*1000);signal?.addEventListener('abort',stop,{once:true});});check(signal);response=await transport(polling,{authenticate,bulk:false,signal});if(response.status===200)break;if(response.status!==202)throw Error('Bulk export did not complete.');}
 if(response?.status!==200)throw Error('Export is still pending after 30 checks. No data accepted; contact the source administrator before starting another job.');
 const manifest=parse(response.body);if(typeof manifest.requiresAccessToken!=='boolean'||typeof manifest.transactionTime!=='string'||!validInstant(manifest.transactionTime)||!Array.isArray(manifest.output)||!Array.isArray(manifest.error))throw Error('Bulk manifest is missing required completion evidence.');
 if(manifest.error.length||manifest.deleted?.length||manifest.link?.length)throw Error('Export has errors, deletion files or partial manifests requiring reconciliation. This preview cannot accept it.');
 if(!manifest.output.length||manifest.output.length>30)throw Error('Bulk export is empty or exceeds 30 files. Request a smaller cohort.');if(manifest.requiresAccessToken&&!authenticate)throw Error('Bulk files require authorization. Authenticate before retrieving them.');
 const out=collect();await out.add('Bulk manifest',response.body);const urls=new Set<string>();let fileIndex=0;
 for(const file of manifest.output){check(signal);if(!types.includes(file.type)||typeof file.url!=='string')throw Error('Manifest returned an unrequested resource type or missing file URL.');const url=approvedUrl(file.url,polling);if(urls.has(url))throw Error('Manifest repeats an output file.');urls.add(url);onProgress?.(`Reading export file ${++fileIndex} of ${manifest.output.length}`);const data=await transport(url,{authenticate:manifest.requiresAccessToken,bulk:false,signal});if(data.status!==200)throw Error('Bulk file download incomplete.');await out.add(`${file.type} file ${fileIndex}`,data.body);const lines=data.body.split(/\r?\n/).filter(l=>l.trim());if(file.count!==undefined&&(!Number.isSafeInteger(file.count)||file.count!==lines.length))throw Error('Bulk file count does not reconcile with its manifest.');for(const line of lines){const r=resource(parse(line));if(r.resourceType!==file.type)throw Error('Bulk file contains a different resource type.');out.push(r);}}
 check(signal);return {sourceId:base,format:'FHIR R4',records:out.records,artifacts:out.artifacts,warnings:['Group membership is controlled by the source hospital; this preview does not authorize a cohort.','Server transaction time is recorded; no refresh watermark is advanced.','This preview does not issue DELETE cleanup or modify the source.'],transactionTime:manifest.transactionTime,complete:true};
}
