import { useState, useRef, useEffect } from 'react';
import { ArrowRight, ArrowLeft, CheckCircle2, Database, ShieldCheck, FileCheck2 } from 'lucide-react';

const steps = ['Welcome', 'Your workflow', 'Ready to begin'];
export function DemoOnboarding({onComplete}:{onComplete:()=>void}) {
  const [step,setStep]=useState(0);
  const body=useRef<HTMLDivElement>(null);
  useEffect(()=>{body.current?.scrollTo({top:0});},[step]);
  return <section className="dc-onboarding" aria-label="Demo introduction">
    <div className="dc-onboarding-top"><span className="dc-eyebrow">GETTING STARTED · ABOUT ONE MINUTE</span><button className="dc-link" onClick={onComplete}>Skip introduction</button></div>
    <ol className="dc-intro-progress">{steps.map((label,index)=><li key={label} aria-current={step===index?'step':undefined} className={index<=step?'active':''}><span>{index<step?<CheckCircle2 size={16}/>:index+1}</span>{label}</li>)}</ol>
    {step===0&&<div ref={body} className="dc-intro-body" tabIndex={0} aria-label="Introduction details"><div><span className="dc-kicker">WELCOME TO DATA COUNTS</span><h2>A clear path from hospital records to a reviewed release.</h2><p>Work through the hospital data-operations workflow: confirm a scoped request, inspect original laboratory records, resolve source issues and review exactly what would be released.</p><p>You’ll work with 12 synthetic patients. The sample request and records are included. Source connection previews and document review are separate tools.</p></div><aside className="dc-intro-card"><Database size={30}/><h3>Ready on this device</h3><ul><li>Example request and laboratory records included</li><li>No hospital login or setup required</li><li>No model download needed</li><li>Original source evidence stays available</li></ul></aside></div>}
    {step===1&&<div ref={body} className="dc-intro-body" tabIndex={0} aria-label="Introduction details"><div><span className="dc-kicker">YOU STAY IN CONTROL</span><h2>Inspect. Resolve. Review.</h2><p>The app guides you through one decision at a time. You can always open the original source record to understand a result.</p><div className="dc-intro-flow"><div><b>1. Understand the request</b><p>See the time period, adult cohort and exact fields.</p></div><div><b>2. Resolve two source issues</b><p>Find a missing unit and a duplicate. Load the supplied correction and check again.</p></div><div><b>3. Review the release</b><p>Account for excluded records, approve the exact package and reconcile a simulated receipt.</p></div></div></div><aside className="dc-intro-card"><ShieldCheck size={30}/><h3>No silent fixes</h3><p>A familiar lab name does not justify inventing a missing unit. Source problems block release until corrected input is provided.</p><p>Approval is yours. Changing permissions invalidates the old approval.</p></aside></div>}
    {step===2&&<div ref={body} className="dc-intro-body" tabIndex={0} aria-label="Introduction details"><div><span className="dc-kicker">YOUR WORKSPACE IS READY</span><h2>Start with what’s being requested.</h2><p>We’ll open the request first. Then inspect the records and run the quality checks. The “Next step” guide will keep you oriented.</p><div className="dc-ready-list"><p><CheckCircle2 size={18}/>Synthetic request and source records are bundled</p><p><CheckCircle2 size={18}/>Checks and package export run locally</p><p><CheckCircle2 size={18}/>You can pause and resume on this device</p></div></div><aside className="dc-intro-card"><FileCheck2 size={30}/><h3>What this demo demonstrates</h3><p>Working quality checks, review gates and export, using synthetic data.</p><p>Broker receipts, privacy tokens and date shifts are illustrative. This alpha is not connected to NIH or a hospital.</p></aside></div>}
    <div className="dc-intro-footer"><span>Step {step+1} of 3 · {steps[step]}</span><div className="dc-actions">{step>0&&<button className="dc-btn" onClick={()=>setStep(s=>s-1)}><ArrowLeft size={16}/>Back</button>}<button className="dc-btn primary" onClick={()=>step===2?onComplete():setStep(s=>s+1)}>{step===2?'Open the example request':'Continue'}<ArrowRight size={16}/></button></div></div>
  </section>;
}
