import {useEffect,useState} from 'react';
import {isTauri} from '@/lib/tauri';
type Status={ready:boolean;freeBytes:number;busy:boolean;phase:string;details?:{version:string}};
export function DoclingSetup({disabled,onReady}:{disabled:boolean;onReady:(value:boolean)=>void}){
 const [status,setStatus]=useState<Status|null>(null),[error,setError]=useState(''),[installing,setInstalling]=useState(false);
 async function check(){if(!isTauri)return;try{const {invoke}=await import('@tauri-apps/api/core');const s=await invoke<Status>('docling_status');setStatus(s);onReady(s.ready);}catch(e){setError(String(e));}}
 useEffect(()=>{void check();},[]);
 useEffect(()=>{if(!installing)return;const timer=setInterval(()=>void check(),2000);return()=>clearInterval(timer);},[installing]);
 async function install(){setError('');setInstalling(true);try{const {invoke}=await import('@tauri-apps/api/core');await invoke('setup_docling');}catch(e){setError(String(e));}finally{setInstalling(false);await check();}}
 return <details className="dc-evidence-card"><summary>Advanced PDF reader · {status?.ready?'Ready':installing?'Setting up':'Setup required'}</summary><p className="mt-3">Docling reads PDF layout, tables and scans locally. Setup downloads a separate Python environment and models. Allow 6 GiB free for setup. This alpha requires Python 3.12; it is detected automatically when installed. Tesseract English is preferred when installed; otherwise the reader uses RapidOCR. The chosen engine is recorded with each document.</p><p className="mt-2">{status?`${(status.freeBytes/1024**3).toFixed(1)} GiB free · ${status.details?.version?`Docling ${status.details.version}`:status.phase}`:'Available in the desktop app.'}</p>{installing&&<p role="status">{status?.phase||'Starting setup'} · this can take several minutes. You may cancel and retry.</p>}{error&&<p role="alert" className="dc-error">{error}</p>}<div className="dc-actions mt-3"><button className="dc-btn" disabled={!isTauri||disabled||installing||status?.busy} onClick={()=>void install()}>{status?.ready?'Repair / verify setup':'Set up advanced reader'}</button><button className="dc-btn" disabled={!isTauri||installing} onClick={()=>void check()}>Check readiness</button>{installing&&<button className="dc-btn" onClick={()=>void import('@tauri-apps/api/core').then(({invoke})=>invoke('cancel_docling')).catch(e=>setError(String(e)))}>Cancel setup</button>}</div><p className="mt-3">Models are downloaded during setup. PDF processing disables network access. No cloud OCR or automatic clinical verification is implied.</p></details>;
}
