import {useEffect,useRef,useState} from 'react';
import {decryptDelivery,MAX_ENCRYPTED_BYTES,newRecoveryKey} from '@/lib/data-counts/encrypted-export';
export function EncryptedExportDialog({onClose,onExport}:{onClose:()=>void;onExport:(key:string)=>Promise<boolean>}){
 const dialog=useRef<HTMLDialogElement>(null);const [key]=useState(newRecoveryKey);const [confirm,setConfirm]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 useEffect(()=>{dialog.current?.showModal();},[]);
 return <dialog ref={dialog} className="dc-confirm-dialog" aria-labelledby="encrypt-title" onCancel={e=>{e.preventDefault();if(!busy)onClose();}}><h2 id="encrypt-title">Protect this demo export</h2><p>Save this recovery key in your approved password manager, separately from the exported file. SiteConnect does not save it. Losing the key means losing access to this export.</p><label className="block mt-4">Recovery key<input className="dc-input mt-2" aria-label="Recovery key" readOnly value={key} spellCheck={false} onFocus={e=>e.target.select()}/></label><label className="block mt-4">Paste your saved key to confirm<input className="dc-input mt-2" aria-label="Confirm recovery key" type="password" autoComplete="off" value={confirm} disabled={busy} onChange={e=>setConfirm(e.target.value)}/></label><p className="mt-4">Encryption protects the file. It does not approve the demo data for external delivery. Anyone holding this key can decrypt or create a file; it is not proof of sender identity.</p>{error&&<p role="alert">{error}</p>}<div className="dc-actions mt-4"><button className="dc-btn" disabled={busy} onClick={onClose}>Cancel</button><button className="dc-btn primary" disabled={busy||confirm!==key} onClick={async()=>{setBusy(true);setError('');try{if(await onExport(key))onClose();else setError('Export was not completed. Keep this key and try again.');}catch{setError('Export failed. Keep this key and try again.');}finally{setBusy(false);}}}>{busy?'Encrypting…':'Save encrypted export'}</button></div></dialog>;
}
export function EncryptedRecovery({onDownload}:{onDownload:(name:string,data:unknown)=>Promise<boolean>}){
 const [copying,setCopying]=useState(false);
 const [file,setFile]=useState<File|null>(null);const [key,setKey]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [result,setResult]=useState<Awaited<ReturnType<typeof decryptDelivery>>|null>(null);const epoch=useRef(0);
 useEffect(()=>()=>{epoch.current++;},[]);
 const clear=()=>{epoch.current++;setResult(null);setError('');};
 return <section className="dc-panel mt-4"><h2>Open an encrypted demo export</h2><p>Choose the .jwe file and its separate recovery key. Opening it here does not restore a session, authorize delivery or confirm who created it.</p><div className="dc-columns mt-4"><label>Encrypted file<input className="dc-input mt-2" type="file" accept=".jwe" disabled={busy} onChange={e=>{clear();setFile(e.target.files?.[0]??null);setKey('');}}/></label><label>Recovery key<input className="dc-input mt-2" type="password" autoComplete="off" value={key} disabled={busy} onChange={e=>{clear();setKey(e.target.value);}}/></label></div><div className="dc-actions mt-4"><button className="dc-btn primary" disabled={busy||!file||!key} onClick={async()=>{clear();const id=epoch.current;setBusy(true);try{if(file!.size>MAX_ENCRYPTED_BYTES)throw Error('Encrypted file exceeds the supported size.');const opened=await decryptDelivery(await file!.text(),key);if(id===epoch.current){setResult(opened);setKey('');}}catch(e){if(id===epoch.current){setError(e instanceof Error?e.message:'Could not open export');setKey('');}}finally{if(id===epoch.current)setBusy(false);}}}>{busy?'Opening…':'Unlock for review'}</button>{result&&<button className="dc-btn" onClick={()=>{clear();setKey('');}}>Close decrypted review</button>}</div>{error&&<p role="alert" className="mt-3">{error}</p>}{result&&<div className="dc-notice mt-4"><div><strong>File opened · {result.count} observations</strong><p>Package {result.packageId}. Encryption integrity checked; sender identity and clinical accuracy are not verified. Decrypted content stays in memory until you close this review.</p><button className="dc-btn mt-3" disabled={copying} onClick={async()=>{const id=epoch.current;setCopying(true);setError('');try{const saved=await onDownload('decrypted-demo-review.json',result.data);if(!saved&&id===epoch.current)setError('The plaintext copy was not saved. Your decrypted review is still available.');}catch{if(id===epoch.current)setError('Could not save the plaintext copy. Your decrypted review is still available.');}finally{setCopying(false);}}}>{copying?'Saving review copy…':'Save plaintext review copy'}</button><p className="mt-2">A plaintext copy contains the prepared clinical data. Keep it in the site review workspace.</p></div></div>}</section>;
}
