import {ConnectionStorage} from './ConnectionStorage';
import {useEffect,useRef,useState} from 'react';
import {ArrowLeft,CheckCircle2,Database,FileInput,Network,KeyRound,Plug,ArrowRight,X} from 'lucide-react';
import {isTauri,listEpicConnections,upsertEpicConnection,type EpicConnection} from '@/lib/tauri';
import {fhirBase,approvedUrl,inspectCapabilities,fetchPatientPreview,fetchBulkPreview,type Transport,type SourcePreview} from '@/lib/connectors/fhir';
import {previewSourceFile} from '@/lib/connectors/files';
import {DEMO_BASE,demoTransport,HL7_SAMPLE} from '@/lib/connectors/demo';
import {sourceBundle} from '@/lib/data-counts/engine';
type Route='fhir'|'bulk'|'hl7'|'file';
async function native<T>(command:string,args:Record<string,unknown>){if(!isTauri)throw Error('Live connections require the native desktop app. Use the synthetic walkthrough here.');const {invoke}=await import('@tauri-apps/api/core');return invoke<T>(command,args);}
const routes=[{id:'fhir',title:'FHIR patient preview',description:'Read a small approved patient list from Epic, Oracle Health or another R4 server.',icon:Database},{id:'bulk',title:'FHIR group export',description:'Preview a hospital-defined cohort using the asynchronous Bulk Data API.',icon:Network},{id:'hl7',title:'HL7 laboratory messages',description:'Inspect ORU R01 message files from the hospital interface team.',icon:Plug},{id:'file',title:'Hospital-managed extract',description:'Inspect FHIR JSON/NDJSON or CSV/TSV without connecting to the source system.',icon:FileInput}] as const;
export function HospitalConnections({onClose}:{onClose:()=>void}){
 const [storageOpen,setStorageOpen]=useState(false),[storageEpoch,setStorageEpoch]=useState(0);
 const [route,setRoute]=useState<Route>('fhir'),[demo,setDemo]=useState(true),[connections,setConnections]=useState<EpicConnection[]>([]),[storageReady,setStorageReady]=useState(false),[storageIssue,setStorageIssue]=useState(''),[connectionId,setConnectionId]=useState(''),[label,setLabel]=useState(''),[base,setBase]=useState(''),[vendor,setVendor]=useState('Epic'),[tokenEndpoint,setTokenEndpoint]=useState(''),[clientId,setClientId]=useState(''),[scopes,setScopes]=useState('system/Patient.rs system/Observation.rs system/DiagnosticReport.rs system/Group.rs');
 const [cap,setCap]=useState<ReturnType<typeof inspectCapabilities>|null>(null),[authenticated,setAuthenticated]=useState(false),[publicKey,setPublicKey]=useState(''),[patients,setPatients]=useState('SYN-003'),[group,setGroup]=useState(''),[since,setSince]=useState(''),[reports,setReports]=useState(false),[preview,setPreview]=useState<SourcePreview|null>(null),[selected,setSelected]=useState(0),[artifact,setArtifact]=useState(0),[rawPage,setRawPage]=useState(0),[busy,setBusy]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const cancel=useRef<AbortController|null>(null),alive=useRef(true);const current=connections.find(c=>c.id===connectionId);
 useEffect(()=>{let active=true;alive.current=true;setStorageReady(false);setStorageIssue('');setConnections([]);if(isTauri&&!demo)void listEpicConnections().then(v=>{if(active){setConnections(v);setStorageReady(true);}}).catch(()=>{if(active)setStorageIssue('Connection storage is locked or unavailable. Set up or unlock local storage here, then continue with the same source configuration.');});return()=>{active=false;alive.current=false;cancel.current?.abort();};},[demo,storageEpoch]);
 function invalidate(){cancel.current?.abort();setPreview(null);setCap(null);setAuthenticated(false);setPublicKey('');setError('');setNotice('');setSelected(0);setArtifact(0);setRawPage(0);}
 const transport:Transport=async(url,options)=>{if(options.signal?.aborted)throw Error('Preview cancelled.');const result=demo?await demoTransport(url,options):await native<Awaited<ReturnType<Transport>>>('hospital_request',{input:{baseUrl:base,url,connectionId:connectionId||null,authenticate:options.authenticate,bulk:options.bulk}});if(options.signal?.aborted)throw Error('Preview cancelled.');return result;};
 async function run(task:(signal:AbortSignal)=>Promise<void>,message:string){if(busy)return;const controller=new AbortController();cancel.current=controller;setBusy(message);setError('');setNotice('');try{await task(controller.signal);}catch(e){if(alive.current)setError(e instanceof Error?e.message:String(e));}finally{if(alive.current)setBusy('');}}
 function choose(id:string){invalidate();setConnectionId(id);const c=connections.find(c=>c.id===id);setBase(c?.fhir_base_url??'');setLabel(c?.site_label??'');setTokenEndpoint(c?.token_url??'');setClientId(c?.client_id??'');setScopes(c?.scopes??'system/Patient.rs system/Observation.rs system/DiagnosticReport.rs system/Group.rs');setPatients('');setGroup('');}
 async function inspect(signal:AbortSignal){setPreview(null);setCap(null);const b=demo?DEMO_BASE:fhirBase(base);const response=await transport(`${b}/metadata`,{authenticate:false,bulk:false,signal});if(response.status!==200)throw Error('Capability discovery did not complete.');const value=inspectCapabilities(response.body);if(!signal.aborted&&alive.current){setCap(value);setNotice('Server capabilities checked. This does not prove authorization to patient data.');}}
 async function retrieve(signal:AbortSignal){setPreview(null);setSelected(0);setArtifact(0);setRawPage(0);const b=demo?DEMO_BASE:fhirBase(base);const result=route==='bulk'?await fetchBulkPreview(b,demo?'synthetic-group':group,since,transport,!demo&&authenticated,signal,m=>{if(alive.current)setBusy(m);}):await fetchPatientPreview(b,patients.split(/[\s,]+/).filter(Boolean),reports,transport,!demo&&authenticated,signal);if(!signal.aborted&&alive.current)setPreview(result);}
 async function loadFile(file:File){await run(async signal=>{setPreview(null);if(file.size>12*1024*1024)throw Error('Choose a file no larger than 12 MiB.');const body=new TextDecoder('utf-8',{fatal:true,ignoreBOM:true}).decode(await file.arrayBuffer());const result=await previewSourceFile(file.name,body);if(!signal.aborted&&alive.current){setSelected(0);setArtifact(0);setRawPage(0);setPreview(result);}},'Checking the complete source file…');}
 const network=route==='fhir'||route==='bulk';const canRead=cap?.resources.some(r=>r.type==='Patient'&&r.read)&&cap?.resources.some(r=>r.type==='Observation'&&r.search)&&(!reports||cap?.resources.some(r=>r.type==='DiagnosticReport'&&r.search));
 return <section className="dc-connections" aria-label="Hospital source connections"><div className="dc-connection-header"><button className="dc-btn" onClick={()=>{cancel.current?.abort();onClose();}}><ArrowLeft size={15}/>Back to source records</button><span className="dc-badge">Read-only source intake</span></div><h2>Connect a hospital source</h2><p>Check access, inspect original records, and identify gaps before a production release. Source previews stay in this view’s memory; they do not enter the synthetic journal or the screening database.</p>
 <div className="dc-connection-routes" role="group" aria-label="Source route">{routes.map(r=><button key={r.id} disabled={!!busy} aria-pressed={route===r.id} onClick={()=>{setPreview(null);setError('');setNotice('');setRoute(r.id);}}><r.icon size={20}/><strong>{r.title}</strong><span>{r.description}</span></button>)}</div>
 <div className="dc-connection-mode"><label><input type="checkbox" checked={demo} disabled={!!busy} onChange={e=>{invalidate();setDemo(e.target.checked);setPatients(e.target.checked?'SYN-003':'');}}/> Use synthetic walkthrough</label><p>{demo?'Bundled fixtures only. No hospital request or authentication is performed.':'Hospital source preview. Use only the endpoint and cohort authorized by your integration team.'}</p></div>
 {!demo&&storageIssue&&<div role="status" className="dc-source-warning">{storageIssue}<button className="dc-btn mt-3" disabled={!!busy} onClick={()=>setStorageOpen(true)}>Set up or unlock storage</button></div>}{!demo&&storageOpen&&<ConnectionStorage onClose={()=>setStorageOpen(false)} onReady={()=>{setStorageOpen(false);setStorageEpoch(n=>n+1);setNotice("Local storage is open. Continue with source configuration; hospital authorization is checked separately.");}}/>}{error&&<div role="alert" className="dc-source-warning">{error}</div>}{notice&&<p role="status" className="dc-connection-notice">{notice}</p>}
 {network?<div className="dc-connection-steps"><section className="dc-panel"><span className="dc-eyebrow">1 · CHECK THE SOURCE</span><h3>{demo?'Explore the connection workflow':'Hospital-approved endpoint'}</h3>{!demo&&<><label className="dc-connection-field">Saved connection<select disabled={!!busy} value={connectionId} onChange={e=>choose(e.target.value)}><option value="">New connection / public capability check</option>{connections.map(c=><option key={c.id} value={c.id}>{c.site_label}</option>)}</select></label><label className="dc-connection-field">Source system<select disabled={!!busy} value={vendor} onChange={e=>setVendor(e.target.value)}><option>Epic</option><option>Oracle Health / Cerner</option><option>Other FHIR R4</option></select></label><label className="dc-connection-field">FHIR R4 base URL<input disabled={!!busy||!!connectionId} value={base} onChange={e=>{invalidate();setBase(e.target.value);}} placeholder="https://hospital.example/fhir/R4" autoComplete="off"/></label><p>The vendor label is descriptive. Enabled resources and authentication must be checked for this hospital.</p></>}
 <button className="dc-btn primary" disabled={!!busy||(!demo&&(!isTauri||!base))} onClick={()=>void run(inspect,'Reading capability statement…')}>Check source capabilities <ArrowRight size={14}/></button>{!demo&&!isTauri&&<p className="mt-3">Open the native app for real endpoint access.</p>}
 {cap&&<div className="dc-capability-result"><strong><CheckCircle2 size={15}/>FHIR {cap.version} · capabilities checked</strong><p>{cap.software}</p><p>Resources advertised: {cap.resources.map(r=>r.type).join(', ')||'None'}</p><p>Group export: {cap.groupExport?'advertised':'not advertised in this statement'}. Capabilities are not proof of data availability.</p></div>}
 </section>
 <section className="dc-panel"><span className="dc-eyebrow">2 · AUTHORIZE ACCESS</span><h3>{demo?'No credentials needed':'Site-controlled backend access'}</h3>{demo?<p>The walkthrough substitutes deterministic source responses. It does not validate Epic or Oracle connectivity.</p>:<><p>Register this client and its public key with hospital IT. Private keys and tokens remain in the native OS credential store. Current signing support is ES384 (P-384); confirm the server accepts it. Servers requiring RS384 are not supported by this preview.</p>{!current&&<><label className="dc-connection-field">Connection name<input disabled={!!busy} value={label} onChange={e=>setLabel(e.target.value)} placeholder="Hospital · laboratory pilot"/></label><label className="dc-connection-field">Approved OAuth token endpoint<input disabled={!!busy} value={tokenEndpoint} onChange={e=>setTokenEndpoint(e.target.value)} placeholder="https://hospital.example/oauth/token" autoComplete="off"/></label><label className="dc-connection-field">Registered client ID<input disabled={!!busy} value={clientId} onChange={e=>setClientId(e.target.value)} autoComplete="off"/></label><label className="dc-connection-field">Approved system read/search scopes<input disabled={!!busy} value={scopes} onChange={e=>setScopes(e.target.value)}/></label><button className="dc-btn" disabled={!!busy||!isTauri||!storageReady||!cap||!label.trim()||!clientId.trim()||!tokenEndpoint} onClick={()=>void run(async()=>{const b=fhirBase(base);approvedUrl(tokenEndpoint);if(scopes.split(/\s+/).some(s=>!/^system\/[^\s]+\.(read|rs|r)$/.test(s)))throw Error('Use approved system read/search scopes only.');const c=await upsertEpicConnection({site_label:label,fhir_base_url:b,token_url:tokenEndpoint,client_id:clientId,scopes,auth_mode:'backend_services',notes:`Source preview · ${vendor}`});if(alive.current){setConnections(v=>[...v,c]);setConnectionId(c.id);setBase(b);setNotice('Connection saved. Prepare its public key and register it with hospital IT.');}},'Saving connection configuration…')}>Save connection configuration</button></>}
 {current&&<><p><strong>{current.site_label}</strong> · configuration saved; authorization is checked separately.</p><div className="dc-actions"><button className="dc-btn" disabled={!!busy} onClick={()=>void run(async()=>{const key=await native('hospital_public_key',{id:connectionId});if(alive.current)setPublicKey(JSON.stringify(key,null,2));},'Preparing registration key…')}><KeyRound size={14}/>Show public registration key</button><button className="dc-btn" disabled={!!busy} onClick={()=>void run(async()=>{const message=await native<string>('hospital_authenticate',{id:connectionId});if(alive.current){setAuthenticated(true);setNotice(message);}},'Authenticating with approved token endpoint…')}>Authenticate access</button>{authenticated&&<button className="dc-btn" disabled={!!busy} onClick={()=>void run(async()=>{await native('hospital_disconnect',{id:connectionId});if(alive.current){setAuthenticated(false);setPreview(null);}},'Removing local authorization…')}>Disconnect authorization</button>}</div>{publicKey&&<details open><summary>Public JWKS for hospital registration</summary><pre>{publicKey}</pre><p>Only the public key is shown. Existing key material is reused; this does not rotate a registered key.</p></details>}{authenticated&&<p className="dc-connection-notice">Authenticated this session. Preview will still check current token expiry and server permissions.</p>}</>}
 </>}
 </section>
 <section className="dc-panel"><span className="dc-eyebrow">3 · PREVIEW ORIGINAL DATA</span><h3>{route==='bulk'?'Hospital-defined group':'Small, explicit patient list'}</h3>{route==='bulk'?<><label className="dc-connection-field">FHIR Group ID<input disabled={demo||!!busy} value={demo?'synthetic-group':group} onChange={e=>{setPreview(null);setGroup(e.target.value);}}/></label><label className="dc-connection-field">Changed since (optional, timezone required)<input disabled={demo||!!busy} value={since} onChange={e=>{setPreview(null);setSince(e.target.value);}} placeholder="2026-09-01T00:00:00Z"/></label><p>Requests Patient, Observation and DiagnosticReport. Up to 30 files and 12 MiB; larger exports require a production ingestion service. Polling stops after 30 checks.</p><p>Cancellation stops this local preview; a hospital export job may continue. No server cleanup or refresh-watermark change is issued.</p></>:<><label className="dc-connection-field">FHIR patient IDs (up to 10)<textarea disabled={!!busy} rows={2} value={patients} onChange={e=>{setPreview(null);setPatients(e.target.value);}} placeholder="Use FHIR logical IDs, not unqualified MRNs"/></label><label className="dc-check"><input type="checkbox" disabled={!!busy} checked={reports} onChange={e=>{setPreview(null);setReports(e.target.checked);}}/>Include DiagnosticReport resources</label><p>Retrieves Patient and all returned Observations for these IDs. This is not a laboratory-only or date-filtered release. No fields are silently removed.</p></>}
 <button className="dc-btn primary" disabled={!!busy||!cap||(!demo&&!authenticated)||(route==='fhir'?!canRead:!cap.groupExport)} onClick={()=>void run(retrieve,'Reading original source records…')}>Retrieve source preview <ArrowRight size={14}/></button>{!cap?<p className="mt-3">First check source capabilities.</p>:!demo&&!authenticated?<p className="mt-3">Next: register the public key with hospital IT, then authenticate access in step 2.</p>:(route==='fhir'?!canRead:!cap.groupExport)?<p className="mt-3">This server does not advertise the required operations. Ask hospital IT to enable them, or use a hospital-managed extract.</p>:null}
 </section></div>:<section className="dc-panel"><span className="dc-eyebrow">LOCAL FILE INTAKE</span><h3>{route==='hl7'?'Inspect an ORU R01 message file':'Inspect a complete hospital extract'}</h3><p>{route==='hl7'?'This build reads message files. A production MLLP feed requires durable intake, acknowledgments and hospital routing; no listener is started.':'Your hospital can deliver an approved extract to a local folder. This build provides manual intake, not an SFTP service or scheduled watcher.'}</p><div className="dc-actions">{demo?<button className="dc-btn primary" disabled={!!busy} onClick={()=>void run(async()=>{const result=await previewSourceFile(route==='hl7'?'synthetic-results.hl7':'synthetic-laboratory.fhir.json',route==='hl7'?HL7_SAMPLE:JSON.stringify(sourceBundle(true,true)));if(alive.current){setPreview(result);setSelected(0);setArtifact(0);setRawPage(0);}},'Validating bundled source…')}>Load synthetic {route==='hl7'?'HL7 messages':'FHIR extract'}</button>:<label className="dc-btn">Choose source file<input aria-label="Choose hospital source file" type="file" disabled={!!busy} accept={route==='hl7'?'.hl7,.txt':'.json,.ndjson,.csv,.tsv'} onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(file)void loadFile(file);}}/></label>}</div></section>}
 {busy&&<div role="status" className="dc-connection-progress">{busy}{/^(Reading|Waiting|Checking)/.test(busy)&&<button className="dc-btn" onClick={()=>{cancel.current?.abort();setNotice('Cancellation requested. The in-flight native request may take up to 30 seconds to stop waiting; a hospital export job may continue.');}}>Cancel preview</button>}</div>}
 {preview&&<section className="dc-panel" aria-label="Source preview"><div className="dc-section-title"><div><span className="dc-eyebrow">SOURCE RETRIEVAL / PARSE COMPLETE</span><h3>{preview.records.length} source records · {preview.artifacts.length} retained artifacts</h3></div><button className="dc-btn" onClick={()=>setPreview(null)}><X size={14}/>Clear preview</button></div><p>Not clinically validated or authorized for release. No synthetic permissions, date shifts or linkage tokens have been applied.</p>{preview.transactionTime&&<p>Server transaction time: {preview.transactionTime}</p>}{preview.warnings.map(w=><p className="mt-2" key={w}>{w}</p>)}<div className="dc-connection-preview"><div><label className="dc-connection-field">Inspect record<select value={selected} onChange={e=>setSelected(Number(e.target.value))}>{preview.records.slice(Math.floor(selected/200)*200,Math.floor(selected/200)*200+200).map((r,index)=>{const i=Math.floor(selected/200)*200+index;return <option key={i} value={i}>{String(r.resourceType??'Row')} · {String(r.id??i+1)}</option>;})}</select></label>{preview.records.length>200&&<div className="dc-actions"><button className="dc-btn" disabled={selected<200} onClick={()=>setSelected((Math.floor(selected/200)-1)*200)}>Previous 200</button><span>Record {selected+1} of {preview.records.length}</span><button className="dc-btn" disabled={Math.floor(selected/200)*200+200>=preview.records.length} onClick={()=>setSelected((Math.floor(selected/200)+1)*200)}>Next 200</button></div>}<pre>{JSON.stringify(preview.records[selected],null,2).slice(0,20000)}</pre></div><div><label className="dc-connection-field">Original source artifact<select value={artifact} onChange={e=>{setArtifact(Number(e.target.value));setRawPage(0);}}>{preview.artifacts.map((a,i)=><option key={i} value={i}>{a.label}</option>)}</select></label><p className="dc-source-hash">SHA-256: {preview.artifacts[artifact]?.sha256}</p><pre>{preview.artifacts[artifact]?.body.slice(rawPage*20000,(rawPage+1)*20000)}</pre><div className="dc-actions"><button className="dc-btn" disabled={!rawPage} onClick={()=>setRawPage(p=>p-1)}>Previous text</button><span>Text page {rawPage+1} of {Math.max(1,Math.ceil((preview.artifacts[artifact]?.body.length??0)/20000))}</span><button className="dc-btn" disabled={(rawPage+1)*20000>=(preview.artifacts[artifact]?.body.length??0)} onClick={()=>setRawPage(p=>p+1)}>Next text</button></div><p>Raw source is shown in 20,000-character pages; parsed record display is limited to 20,000 characters. Valid UTF-8 source payload text, including any BOM, is retained separately.</p></div></div><p className="mt-3">Next: confirm source completeness, patient authority and the approved request with hospital IT. Real-source release remains disabled until those integrations and privacy controls are validated.</p></section>}
 </section>;
}
