import {useState} from 'react';
import {REQUEST} from '@/lib/data-counts/engine';
import {requestFindings,FIELD_LABELS,type ExceptionNote} from '@/lib/extraction/request-review';
import type {SourceFile,Entity} from '@/lib/extraction/types';
export function RequestReview({source,entities,complete,scoped,rejected,notes,onNote,onSelect,disabled}:{source:SourceFile;entities:Entity[];complete:boolean;scoped:boolean;rejected:string[];notes:ExceptionNote[];onNote:(note:ExceptionNote)=>void;onSelect:(id:string)=>void;disabled:boolean}){
 const [field,setField]=useState(''),[reason,setReason]=useState(''),[state,setState]=useState<ExceptionNote['state']>('Not found');
 const findings=requestFindings(source,entities,complete,rejected,scoped);
 return <section className="dc-request-review"><span className="dc-eyebrow">REQUEST EVIDENCE</span><h3>{REQUEST.label}</h3><p>{REQUEST.id} · revision {REQUEST.version} · {REQUEST.start} through {REQUEST.end}</p><p className="mt-2">{REQUEST.cohort}. This checklist shows document evidence, not an eligibility decision or release approval.</p><div className="dc-request-findings">{findings.map(f=>{const note=notes.filter(n=>n.field===f.field).at(-1);return <article key={f.field}><div><strong>{f.label}</strong><span className={`dc-finding-state ${f.state==='Evidence found'?'found':''}`}>{note&&note.state!=='Resolved'?`Reviewer: ${note.state}`:f.state}</span></div><p>{f.detail}</p>{note&&<p className="dc-review-reason">Reviewer note: {note.reason}</p>}<div className="dc-actions">{f.entityIds.length>0&&<button className="dc-btn" onClick={()=>onSelect(f.entityIds[0]!)}>Inspect evidence ({f.entityIds.length})</button>}<button className="dc-btn" disabled={disabled||!complete} onClick={()=>{setField(f.field);setReason('');setState('Not found');}}>Record open question</button></div></article>;})}</div>
 {field&&<form className="dc-evidence-card" onSubmit={e=>{e.preventDefault();if(reason.trim().length<5)return;onNote({field,state,reason:reason.trim(),at:new Date().toISOString(),sourceHash:source.hash});setField('');}}><h3>Open question · {FIELD_LABELS[field]}</h3><label>Status<select className="dc-input" value={state} onChange={e=>setState(e.target.value as ExceptionNote['state'])}><option>Not found</option><option>Uncertain</option>{notes.some(n=>n.field===field)&&<option>Resolved</option>}{['Observation.referenceRange','Observation.dataAbsentReason'].includes(field)&&<option>Not applicable</option>}</select></label><label>Reason and next action<textarea className="dc-input" required minLength={5} value={reason} onChange={e=>setReason(e.target.value)} placeholder="What did you check, and what source or answer is still needed?"/></label><p>A note records the gap; it does not supply a missing value or authorize release.</p><div className="dc-actions mt-3"><button className="dc-btn primary" disabled={disabled||reason.trim().length<5}>Save question</button><button type="button" className="dc-btn" onClick={()=>setField('')}>Cancel</button></div></form>}
 </section>;
}
