import {directCandidates,mergeCandidates,uncoveredMeasurements,RECALL_VERSION} from '@/lib/extraction/recall';
import {RequestReview} from './RequestReview';
import {AnnotationEditor} from './AnnotationEditor';
import {concern,REQUEST_KEY,requestFindings,type AnnotationChange,type ExceptionNote} from '@/lib/extraction/request-review';
import {REQUEST} from '@/lib/data-counts/engine';
import {useEffect,useRef,useState} from 'react';
import {Upload,FileSearch,ArrowRight,Download} from 'lucide-react';
import {isTauri} from '@/lib/tauri';
import {DoclingSetup} from './DoclingSetup';
import {readWithDocling} from '@/lib/extraction/docling';
import {readSource} from '@/lib/extraction/readers';
import {chunks,validateEntities} from '@/lib/extraction/review';
import type {Entity,SourceFile} from '@/lib/extraction/types';
import profile from '@/lib/extraction/profile.json';
import {NOTE,type Lab} from '@/lib/data-counts/engine';
export type ImportedSource={name:string;hash:string;rows:Lab[];evidence:string};
export function SourceWorkbench({onUseSource,pendingReceipt=false}:{onUseSource?:(source:ImportedSource)=>void;pendingReceipt?:boolean}){
 const [source,setSource]=useState<SourceFile|null>(null),[entities,setEntities]=useState<Entity[]>([]),[selected,setSelected]=useState(''),[manualSegment,setManualSegment]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[complete,setComplete]=useState(false),[query,setQuery]=useState(''),[reviewed,setReviewed]=useState<string[]>([]),[rejected,setRejected]=useState<string[]>([]),[parsedReviewed,setParsedReviewed]=useState(false),[status,setStatus]=useState(''),[seconds,setSeconds]=useState(0),[metrics,setMetrics]=useState<{model:string;latency_ms:number;profile:string}[]>([]),[synthetic,setSynthetic]=useState(false),[notice,setNotice]=useState('');
 const [advanced,setAdvanced]=useState(isTauri),[doclingReady,setDoclingReady]=useState(false);
 const [scoped,setScoped]=useState(true),[runScoped,setRunScoped]=useState(false),[changes,setChanges]=useState<AnnotationChange[]>([]),[notes,setNotes]=useState<ExceptionNote[]>([]),[editor,setEditor]=useState<{id:string;mode:'correct'|'reject'}|null>(null),[inbox,setInbox]=useState('All candidates');
 const effective=entities.map(e=>changes.filter(c=>c.entityId===e.id&&c.action==='correct').at(-1)?.after||e);
 const input=useRef<HTMLInputElement>(null),sequence=useRef(0),job=useRef<string|null>(null),sourcePane=useRef<HTMLDivElement>(null);
 useEffect(()=>{if(!busy)return;const start=Date.now();const timer=setInterval(()=>setSeconds(Math.floor((Date.now()-start)/1000)),1000);return()=>clearInterval(timer);},[busy]);
 useEffect(()=>()=>{sequence.current++;if(isTauri)void import('@tauri-apps/api/core').then(({invoke})=>invoke('cancel_docling')).catch(()=>{});if(job.current&&isTauri)void import('@tauri-apps/api/core').then(({invoke})=>invoke('cancel_source_extraction',{jobId:job.current}));},[]);
 const active=effective.find(e=>e.id===selected);const segment=source?.segments.find(s=>s.id===active?.segment_id)||source?.segments.find(s=>s.id===manualSegment)||source?.segments[0];
 useEffect(()=>{sourcePane.current?.scrollTo({top:0});sourcePane.current?.querySelector('mark')?.scrollIntoView({block:'nearest'});},[selected,manualSegment]);
 async function load(file:File){const n=++sequence.current;setError('');setNotice('');setBusy(true);setStatus('Reading source and preserving locations');setSource(null);setEntities([]);setSelected('');setManualSegment('');setComplete(false);setReviewed([]);setRejected([]);setParsedReviewed(false);setMetrics([]);setQuery('');setChanges([]);setNotes([]);setEditor(null);setRunScoped(false);setInbox('All candidates');
  try{if(advanced&&file.name.toLowerCase().endsWith('.pdf')&&!doclingReady)throw Error('Set up the advanced PDF reader below, or explicitly select the basic reader.');const doc=await (advanced&&file.name.toLowerCase().endsWith('.pdf')?readWithDocling(file):readSource(file));if(n!==sequence.current)return;setSource(doc);const initial=doc.mode==='structured'?doc.entities:directCandidates(doc.segments);setEntities(initial);setSelected(initial[0]?.id||'');setComplete(doc.mode==='structured');setStatus(doc.mode==='structured'?'Parsed source fields. No model was used.':'Source-rule candidates are ready. Run the local model to add interpretation and other facts; all candidates need review.');}catch(e){if(n===sequence.current)setError(String(e));}finally{if(n===sequence.current)setBusy(false);}
 }
 async function extract(){if(!source||!isTauri)return;const n=++sequence.current;setBusy(true);setError('');setNotice('');setComplete(false);setEntities([]);setReviewed([]);setRejected([]);setMetrics([]);setParsedReviewed(false);setSeconds(0);setChanges([]);setNotes([]);setEditor(null);setRunScoped(scoped);setInbox('All candidates');
  try{const {invoke}=await import('@tauri-apps/api/core');const batches=chunks(source.segments,3000);const rules=directCandidates(source.segments);const collected:Entity[]=[];setEntities(rules);setSelected(rules[0]?.id||'');
   for(let i=0;i<batches.length;i++){if(n!==sequence.current)return;setStatus(`Extracting section ${i+1} of ${batches.length}`);const id=crypto.randomUUID();job.current=id;
    const response=await invoke<{result:unknown;model:string;latency_ms:number;profile:string}>('extract_source_entities',{jobId:id,requestKey:scoped?REQUEST_KEY:null,segments:batches[i]!.map(({id,text})=>({id,text}))});if(n!==sequence.current)return;
    const rows=validateEntities(response.result,batches[i]!).map((e,j)=>({...e,id:`batch-${i}-${j}`}));if(rows.length===24)throw Error('This section reached the entity limit. Split it into smaller files before accepting results.');collected.push(...rows);const combined=mergeCandidates(rules,collected);setEntities(combined);setSelected(combined[0]?.id||'');setMetrics(m=>[...m,{model:response.model,latency_ms:response.latency_ms,profile:response.profile}]);
   }setComplete(true);setStatus('Extraction complete. Direct source rules recover supported values the model missed. Review every candidate and its context.');
  }catch(e){if(n===sequence.current){setError(String(e));setStatus('Incomplete extraction — export is paused.');}}finally{if(n===sequence.current){job.current=null;setBusy(false);}}
 }
 async function cancel(){if(isTauri)void import('@tauri-apps/api/core').then(({invoke})=>invoke('cancel_docling')).catch(e=>setError(String(e)));sequence.current++;setBusy(false);setComplete(false);setStatus('Cancelled. Partial results remain visible, but cannot be exported as reviewed.');if(job.current){const id=job.current;job.current=null;try{const {invoke}=await import('@tauri-apps/api/core');await invoke('cancel_source_extraction',{jobId:id});}catch(e){setError(String(e));}}}
 const visible=effective.filter(e=>inbox==='All candidates'||(inbox==='Reviewed'?(reviewed.includes(e.id)||rejected.includes(e.id)):!reviewed.includes(e.id)&&!rejected.includes(e.id)&&(inbox==='Awaiting review'||concern(e)===inbox))).filter(e=>`${e.label} ${e.value} ${e.kind} ${e.assertion}`.toLowerCase().includes(query.toLowerCase()));
 const supported=effective.filter(e=>e.supported);const coverage=!!source&&!source.warnings.some(w=>/OCR|Tracked changes|Coverage is incomplete/.test(w));
 const allReviewed=source?.mode==='structured'?parsedReviewed:effective.length?effective.every(e=>rejected.includes(e.id)||(e.supported&&reviewed.includes(e.id))):parsedReviewed;
 const unresolvedQuestions=notes.filter((n,i)=>!notes.slice(i+1).some(v=>v.field===n.field)&&!['Resolved','Not applicable'].includes(n.state));
 const canExport=complete&&coverage&&allReviewed&&!busy;
 function packet(){return {format:'siteconnect-source-review/2',request:{definition:REQUEST,requestKey:REQUEST_KEY,focusedExtraction:runScoped,findings:requestFindings(source!,effective,complete,rejected,runScoped),openQuestions:notes},reviewerChanges:changes,reviewedAnnotations:effective,synthetic:true,source:{name:source!.name,sha256:source!.hash,format:source!.format,segments:source!.segments.map(({image:_,...s})=>s),original:source!.original},documentReader:source!.documentReader,processing:{recallProfile:RECALL_VERSION,uncoveredMeasurements:uncoveredMeasurements(source!.segments,effective),mode:source!.mode,profile:metrics[0]?.profile||null,metrics,complete,coverage},annotations:entities,review:{scope:'Synthetic operator review, not hospital authorization',reviewedAt:new Date().toISOString(),acceptedIds:source!.mode==='structured'?entities.map(e=>e.id):reviewed,rejectedIds:rejected},warnings:source!.warnings};}
 async function exportReview(){setError('');try{const content=JSON.stringify(packet(),null,2);if(isTauri){const {save}=await import('@tauri-apps/plugin-dialog');const path=await save({defaultPath:'synthetic-source-review.json',filters:[{name:'JSON',extensions:['json']}]});if(!path){setNotice('Export cancelled. Review remains available.');return;}const {writeTextFile}=await import('@tauri-apps/plugin-fs');await writeTextFile(path,content);}else{const url=URL.createObjectURL(new Blob([content],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='synthetic-source-review.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}setNotice('Reviewed evidence exported, including rejected suggestions. No hospital data release or external transmission occurred.');}catch(e){setError(`Export failed: ${String(e)}`);}}
 function useSource(){if(!source?.releaseRows||!canExport||unresolvedQuestions.length)return;const evidence=JSON.stringify({format:"siteconnect-release-source/2",requestReview:{requestKey:REQUEST_KEY,openQuestions:notes},source:{name:source.name,sha256:source.hash,format:source.format,original:source.original||source.segments.map(({id,label,text})=>({id,label,text}))},warnings:source.warnings,processing:{mode:"parser",profile:profile.version},reviewedAt:new Date().toISOString()});if(evidence.length>900000){setError('Evidence exceeds this synthetic journal limit. Use a smaller extract.');return;}onUseSource?.({name:source.name,hash:source.hash,rows:source.releaseRows,evidence});setNotice('Source loaded. Run laboratory quality checks and review a new package.');}
 return <section className="dc-panel"><span className="dc-eyebrow"><FileSearch size={16}/> SOURCE REVIEW · LOCAL PROCESSING</span><h2>Every extracted field has a place to return to.</h2><p>Open a synthetic file. Structured fields are parsed directly; narrative content combines direct source rules with local AI. Select a result to see its source location. AI annotations stay separate from original records.</p>
 <label className="dc-check"><input type="checkbox" checked={synthetic} disabled={busy} onChange={e=>setSynthetic(e.target.checked)}/>I am using synthetic demonstration files, not patient information.</label>
 <label className="dc-check"><input type="checkbox" checked={scoped} disabled={busy} onChange={e=>setScoped(e.target.checked)}/>Focus the next extraction on the active laboratory request (fields, identifiers and source context).</label>
 <DoclingSetup disabled={busy} onReady={setDoclingReady}/><label className="dc-check"><input type="checkbox" checked={advanced} disabled={busy||!isTauri} onChange={e=>setAdvanced(e.target.checked)}/>Use advanced PDF layout and OCR (Docling). Uncheck to use the basic text reader.</label>
 <div className="dc-actions"><input ref={input} type="file" hidden accept=".pdf,.docx,.txt,.md,.markdown,.csv,.tsv,.xlsx,.json,.ndjson,.hl7" onChange={e=>{const f=e.target.files?.[0];if(f&&synthetic)void load(f);e.target.value='';}}/><button className="dc-btn primary" disabled={!synthetic||busy} onClick={()=>input.current?.click()}><Upload size={15}/>Open synthetic file</button><button className="dc-btn" disabled={busy} onClick={()=>{setSynthetic(true);void load(new File([NOTE],'synthetic-lab-note.txt',{type:'text/plain'}));}}>Load example note</button>{source?.mode==='narrative'&&<button className="dc-btn primary" disabled={busy||!isTauri||!synthetic} onClick={()=>void extract()}>Extract with local model <ArrowRight size={14}/></button>}{busy&&<button className="dc-btn" onClick={()=>void cancel()}>Cancel processing</button>}</div>
 <p className="mt-3">Text PDF, DOCX, TXT/Markdown · CSV/TSV, XLSX · FHIR JSON/NDJSON · HL7 files. Up to 12 MB and 30 PDF pages. Scanned PDFs require the advanced reader. Other image formats are not yet enabled.</p>
 {!isTauri&&<p className="mt-2">Browser: source parsing and evidence review work; live model extraction requires the desktop app.</p>}
 {error&&<p role="alert" className="dc-error">{error}</p>}{notice&&<p role="status" className="dc-notice mt-3">{notice}</p>}
 {source&&<><div className="dc-file-summary"><div><strong>{source.name}</strong><p>{source.format.toUpperCase()} · {source.segments.length} source locations · {entities.length} fields / entities</p></div><span>{source.mode==='structured'?'Deterministic parser':'Source rules + local model'}</span></div><p role="status">{status}{busy?` · ${seconds}s elapsed`:''}</p>{metrics.length>0&&<p className="mt-2">{metrics[0]!.model} · {(metrics.reduce((n,m)=>n+m.latency_ms,0)/1000).toFixed(1)}s across {metrics.length} section(s) · {supported.length}/{entities.length} exact-source matches. Matching text does not prove clinical interpretation.</p>}{source.documentReader&&<div className="dc-source-warning"><strong>Docling · {source.documentReader.ocr} · {source.documentReader.elapsedSeconds.toFixed(1)}s</strong><p>{source.documentReader.verification}</p><p>Locations identify document blocks or table regions. Extracted text, OCR and header associations need visual review against the original page.</p></div>}{complete&&uncoveredMeasurements(source.segments,effective).length>0&&<div className="dc-source-warning"><strong>Some measurement-like text needs inspection</strong><p>The coverage check found {uncoveredMeasurements(source.segments,effective).length} numeric/unit passage(s) without a supported candidate. This is a limited coverage check, not a completeness guarantee.</p>{uncoveredMeasurements(source.segments,effective).map((g,i)=><button key={i} className="dc-btn" onClick={()=>{setSelected('');setManualSegment(g.segment_id);}}>{g.text} · inspect source</button>)}</div>}{source.warnings.map((w,i)=><p className="dc-source-warning" key={i}>{w}</p>)}
 <details className="dc-evidence-card"><summary>Request coverage and open questions · {REQUEST.fields.length} requested fields</summary><RequestReview source={source} entities={effective} complete={complete} scoped={runScoped} rejected={rejected} notes={notes} onNote={n=>setNotes(v=>[...v,n])} onSelect={id=>{setSelected(id);setInbox('All candidates');setQuery('');sourcePane.current?.scrollIntoView({block:'center',behavior:'smooth'});}} disabled={busy}/></details>
 {source.mode==='narrative'&&<section className="dc-inbox"><h3>Reviewer inbox</h3><p>{effective.filter(e=>!reviewed.includes(e.id)&&!rejected.includes(e.id)).length} awaiting a decision · {reviewed.length} reviewed · {rejected.length} rejected. Start with source mismatches, then review context and missing units.</p><div className="dc-actions mt-3">{['All candidates','Awaiting review','Source mismatch','Missing source unit','Uncertain context','Historical / superseded context','Patient association to review','Reviewed'].map(group=>{const count=effective.filter(e=>group==='All candidates'||(group==='Reviewed'?(reviewed.includes(e.id)||rejected.includes(e.id)):!reviewed.includes(e.id)&&!rejected.includes(e.id)&&(group==='Awaiting review'||concern(e)===group))).length;return <button key={group} className={`dc-btn ${inbox===group?'primary':''}`} onClick={()=>setInbox(group)}>{group} ({count})</button>;})}</div></section>}
 {editor&&<AnnotationEditor key={`${editor.id}-${editor.mode}`} entity={effective.find(e=>e.id===editor.id)!} source={source} mode={editor.mode} onCancel={()=>setEditor(null)} onSave={change=>{setChanges(v=>[...v,change]);setReviewed(v=>v.filter(id=>id!==change.entityId));setRejected(v=>change.action==='reject'?[...v.filter(id=>id!==change.entityId),change.entityId]:v.filter(id=>id!==change.entityId));setEditor(null);setNotice(change.action==='correct'?'Correction saved separately. Review it against the source before accepting.':'Rejection recorded with its reason.');}}/>}
 <div className="dc-evidence-workspace"><div><label htmlFor="entity-search">Find a field or entity</label><input id="entity-search" className="dc-input mt-2" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Test, value, field name or context…"/><div className="dc-entity-list">{visible.slice(0,150).map(e=><article key={e.id} className={selected===e.id?'selected':''}><button className="dc-entity-target" onClick={()=>setSelected(e.id)}><small>{e.origin==='rule'?'Source rule · context needs review':e.kind} · {e.assertion}{changes.some(c=>c.entityId===e.id&&c.action==='correct')?' · reviewer corrected':''}</small><strong>{e.label}</strong><span>{e.value}{e.unit?` ${e.unit}`:''}</span><small>{e.supported?'View source location →':e.problem}</small></button>{e.origin!=='parser'&&<><label className="dc-check"><input type="checkbox" disabled={!e.supported||!complete||!coverage||rejected.includes(e.id)} checked={reviewed.includes(e.id)} onChange={event=>setReviewed(r=>event.target.checked?[...r,e.id]:r.filter(id=>id!==e.id))}/>I reviewed this entity and its context.</label><button className="dc-btn" disabled={!complete||busy} onClick={()=>{if(rejected.includes(e.id)){setRejected(r=>r.filter(id=>id!==e.id));setReviewed(r=>r.filter(id=>id!==e.id));setChanges(c=>[...c,{entityId:e.id,action:'reopen',reason:'Reviewer reopened a rejected suggestion for a new decision',sourceHash:source.hash,at:new Date().toISOString(),before:e}]);}else{setSelected(e.id);setEditor({id:e.id,mode:'reject'});}}}>{rejected.includes(e.id)?'Reopen suggestion':'Reject with reason'}</button><button className="dc-btn" disabled={!complete||busy||!coverage} onClick={()=>{setSelected(e.id);setEditor({id:e.id,mode:'correct'});}}>Correct annotation</button></>}</article>)}{visible.length>150&&<p>Showing 150 of {visible.length}. Narrow the search to inspect another field.</p>}{!entities.length&&<div className="dc-empty"><FileSearch size={28}/><h3>{complete?'No entities returned':'Source ready for review'}</h3><p>{complete?'No facts were returned. This does not prove that the document contains no relevant facts.':'Run extraction to see candidate entities and click-through evidence.'}</p></div>}</div>{source.mode==='narrative'&&complete&&!entities.length&&<label className="dc-check"><input type="checkbox" checked={parsedReviewed} disabled={!coverage} onChange={e=>setParsedReviewed(e.target.checked)}/>I reviewed the source and open questions despite no returned candidates.</label>}{source.mode==='structured'&&<label className="dc-check"><input type="checkbox" checked={parsedReviewed} disabled={!complete||!coverage} onChange={e=>setParsedReviewed(e.target.checked)}/>I reviewed the parsed source fields and file coverage.</label>}</div>

 <div className="dc-source-viewer" ref={sourcePane} aria-label="Original source viewer" tabIndex={0}>{segment&&<><div className="dc-source-heading"><label htmlFor="source-location">Source location</label><select id="source-location" className="dc-input mt-2 mb-3" value={segment.id} onChange={e=>{setSelected('');setManualSegment(e.target.value);}}>{source.segments.map(s=><option key={s.id} value={s.id}>{s.label}</option>)}</select><strong>{segment.label}</strong><p>{source.name} · original source location</p></div>{segment.image?<div className="dc-pdf-page"><img src={segment.image} alt={`Original ${segment.label}`}/>{(active?.supported||(!active&&source.documentReader))&&segment.runs?.filter(r=>!active||(r.end>active.start&&r.start<active.end)).map((r,i)=><span key={i} className="dc-pdf-highlight" style={{left:`${r.box.x/segment.pageWidth!*100}%`,top:`${r.box.y/segment.pageHeight!*100}%`,width:`${r.box.width/segment.pageWidth!*100}%`,height:`${r.box.height/segment.pageHeight!*100}%`}}/>)}</div>:<pre>{active?.supported?<>{segment.text.slice(0,active.start)}<mark>{segment.text.slice(active.start,active.end)}</mark>{segment.text.slice(active.end)}</>:segment.text}</pre>}{active&&<div className="dc-source-context"><h3>Evidence and context</h3><p>{active.quote}</p><p className="mt-2">{active.subject?`Source subject: ${active.subject}`:'Patient association is not established by this annotation.'}</p>{active.origin!=='parser'&&<p className="mt-2">Assertion: {active.assertion}. Review negation, timing and attribution in the original source before accepting.</p>}</div>}</>}</div></div>
 <div className="dc-actions mt-4"><button className="dc-btn primary" disabled={!canExport} onClick={()=>void exportReview()}><Download size={15}/>Export review & open questions</button>{source.releaseRows&&onUseSource&&<button className="dc-btn" disabled={!canExport||pendingReceipt||unresolvedQuestions.length>0} onClick={useSource}>Use as laboratory source <ArrowRight size={14}/></button>}</div>{unresolvedQuestions.length>0&&<p className="dc-source-warning">{unresolvedQuestions.length} open reviewer question(s). You can export the review, but resolve these before loading a laboratory source.</p>}{!coverage&&<p className="dc-source-warning">File coverage is incomplete or ambiguous. Reviewed export is blocked; use a complete text source.</p>}{source.releaseProblem&&<p className="mt-3">Laboratory release: {source.releaseProblem}</p>}{pendingReceipt&&<p className="mt-3">Reconcile the pending receipt before changing the laboratory source.</p>}
 <details className="mt-4"><summary>Extraction settings and traceability</summary><p>SHA-256: {source.hash}</p><p>Source rules {RECALL_VERSION} copy supported measurements and labeled fields with exact offsets; assertion and patient association remain unconfirmed. Smaller 3,000-byte model batches reduce competing facts. The measurement coverage check is limited to recognized unit patterns.</p><p>Profile {metrics[0]?.profile||profile.version}: document-bound JSON Schema enforced by Ollama; distinct measurement/context shapes; derived categories supplied by software; temperature 0; reasoning enabled; 8,192-token context; 4,096-token output cap; sequential bounded sections; 180 seconds per attempt with at most one source-grounding repair. Truncated or invalid responses fail closed.</p><p>Evidence remains in memory until exported or loaded into the synthetic journal. Original file hash, segment locations and annotation origin accompany the review. This is not approved de-identification, hospital authorization or clinical validation.</p></details></>}
 </section>;
}
