import {useEffect,useRef,useState} from 'react';
import {Upload,FileSearch,ArrowRight,Download} from 'lucide-react';
import {isTauri} from '@/lib/tauri';
import {DoclingSetup} from './DoclingSetup';
import {readWithDocling} from '@/lib/extraction/docling';
import {readSource} from '@/lib/extraction/readers';
import {chunks,validateEntities} from '@/lib/extraction/review';
import type {Entity,SourceFile} from '@/lib/extraction/types';
import profile from '@/lib/extraction/profile.json';
import {NOTE,type Lab} from '@/lib/data-counts/engine';
export type ImportedSource={name:string;hash:string;rows:Lab[];evidence:string};
export function SourceWorkbench({onUseSource,pendingReceipt=false}:{onUseSource?:(source:ImportedSource)=>void;pendingReceipt?:boolean}){
 const [source,setSource]=useState<SourceFile|null>(null),[entities,setEntities]=useState<Entity[]>([]),[selected,setSelected]=useState(''),[manualSegment,setManualSegment]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[complete,setComplete]=useState(false),[query,setQuery]=useState(''),[reviewed,setReviewed]=useState<string[]>([]),[rejected,setRejected]=useState<string[]>([]),[parsedReviewed,setParsedReviewed]=useState(false),[status,setStatus]=useState(''),[seconds,setSeconds]=useState(0),[metrics,setMetrics]=useState<{model:string;latency_ms:number;profile:string}[]>([]),[synthetic,setSynthetic]=useState(false),[notice,setNotice]=useState('');
 const [advanced,setAdvanced]=useState(isTauri),[doclingReady,setDoclingReady]=useState(false);
 const input=useRef<HTMLInputElement>(null),sequence=useRef(0),job=useRef<string|null>(null),sourcePane=useRef<HTMLDivElement>(null);
 useEffect(()=>{if(!busy)return;const start=Date.now();const timer=setInterval(()=>setSeconds(Math.floor((Date.now()-start)/1000)),1000);return()=>clearInterval(timer);},[busy]);
 useEffect(()=>()=>{sequence.current++;if(isTauri)void import('@tauri-apps/api/core').then(({invoke})=>invoke('cancel_docling')).catch(()=>{});if(job.current&&isTauri)void import('@tauri-apps/api/core').then(({invoke})=>invoke('cancel_source_extraction',{jobId:job.current}));},[]);
 const active=entities.find(e=>e.id===selected);const segment=source?.segments.find(s=>s.id===active?.segment_id)||source?.segments.find(s=>s.id===manualSegment)||source?.segments[0];
 useEffect(()=>{sourcePane.current?.scrollTo({top:0});sourcePane.current?.querySelector('mark')?.scrollIntoView({block:'nearest'});},[selected,manualSegment]);
 async function load(file:File){const n=++sequence.current;setError('');setNotice('');setBusy(true);setStatus('Reading source and preserving locations');setSource(null);setEntities([]);setSelected('');setManualSegment('');setComplete(false);setReviewed([]);setRejected([]);setParsedReviewed(false);setMetrics([]);setQuery('');
  try{if(advanced&&file.name.toLowerCase().endsWith('.pdf')&&!doclingReady)throw Error('Set up the advanced PDF reader below, or explicitly select the basic reader.');const doc=await (advanced&&file.name.toLowerCase().endsWith('.pdf')?readWithDocling(file):readSource(file));if(n!==sequence.current)return;setSource(doc);setEntities(doc.entities);setSelected(doc.entities[0]?.id||'');setComplete(doc.mode==='structured');setStatus(doc.mode==='structured'?'Parsed source fields. No model was used.':'Ready for local extraction');}catch(e){if(n===sequence.current)setError(String(e));}finally{if(n===sequence.current)setBusy(false);}
 }
 async function extract(){if(!source||!isTauri)return;const n=++sequence.current;setBusy(true);setError('');setNotice('');setComplete(false);setEntities([]);setReviewed([]);setRejected([]);setMetrics([]);setSeconds(0);
  try{const {invoke}=await import('@tauri-apps/api/core');const batches=chunks(source.segments);const collected:Entity[]=[];
   for(let i=0;i<batches.length;i++){if(n!==sequence.current)return;setStatus(`Extracting section ${i+1} of ${batches.length}`);const id=crypto.randomUUID();job.current=id;
    const response=await invoke<{result:unknown;model:string;latency_ms:number;profile:string}>('extract_source_entities',{jobId:id,segments:batches[i]!.map(({id,text})=>({id,text}))});if(n!==sequence.current)return;
    const rows=validateEntities(response.result,batches[i]!).map((e,j)=>({...e,id:`batch-${i}-${j}`}));if(rows.length===24)throw Error('This section reached the entity limit. Split it into smaller files before accepting results.');collected.push(...rows);setEntities([...collected]);setSelected(collected[0]?.id||'');setMetrics(m=>[...m,{model:response.model,latency_ms:response.latency_ms,profile:response.profile}]);
   }setComplete(true);setStatus('Extraction complete. Review evidence and context before accepting.');
  }catch(e){if(n===sequence.current){setError(String(e));setStatus('Incomplete extraction — export is paused.');}}finally{if(n===sequence.current){job.current=null;setBusy(false);}}
 }
 async function cancel(){if(isTauri)void import('@tauri-apps/api/core').then(({invoke})=>invoke('cancel_docling')).catch(e=>setError(String(e)));sequence.current++;setBusy(false);setComplete(false);setStatus('Cancelled. Partial results remain visible, but cannot be exported as reviewed.');if(job.current){const id=job.current;job.current=null;try{const {invoke}=await import('@tauri-apps/api/core');await invoke('cancel_source_extraction',{jobId:id});}catch(e){setError(String(e));}}}
 const visible=entities.filter(e=>`${e.label} ${e.value} ${e.kind} ${e.assertion}`.toLowerCase().includes(query.toLowerCase()));
 const supported=entities.filter(e=>e.supported);const coverage=!!source&&!source.warnings.some(w=>/OCR|Tracked changes|Coverage is incomplete/.test(w));
 const allReviewed=source?.mode==='structured'?parsedReviewed:entities.length>0&&entities.every(e=>rejected.includes(e.id)||(e.supported&&reviewed.includes(e.id)));
 const canExport=complete&&coverage&&allReviewed&&!busy;
 function packet(){return {format:'siteconnect-source-review/1',synthetic:true,source:{name:source!.name,sha256:source!.hash,format:source!.format,segments:source!.segments.map(({image:_,...s})=>s),original:source!.original},documentReader:source!.documentReader,processing:{mode:source!.mode,profile:profile.version,metrics,complete,coverage},annotations:entities,review:{scope:'Synthetic operator review, not hospital authorization',reviewedAt:new Date().toISOString(),acceptedIds:source!.mode==='structured'?entities.map(e=>e.id):reviewed,rejectedIds:rejected},warnings:source!.warnings};}
 async function exportReview(){setError('');try{const content=JSON.stringify(packet(),null,2);if(isTauri){const {save}=await import('@tauri-apps/plugin-dialog');const path=await save({defaultPath:'synthetic-source-review.json',filters:[{name:'JSON',extensions:['json']}]});if(!path){setNotice('Export cancelled. Review remains available.');return;}const {writeTextFile}=await import('@tauri-apps/plugin-fs');await writeTextFile(path,content);}else{const url=URL.createObjectURL(new Blob([content],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='synthetic-source-review.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}setNotice('Reviewed evidence exported, including rejected suggestions. No hospital data release or external transmission occurred.');}catch(e){setError(`Export failed: ${String(e)}`);}}
 function useSource(){if(!source?.releaseRows||!canExport)return;const evidence=JSON.stringify({format:"siteconnect-release-source/1",source:{name:source.name,sha256:source.hash,format:source.format,original:source.original||source.segments.map(({id,label,text})=>({id,label,text}))},warnings:source.warnings,processing:{mode:"parser",profile:profile.version},reviewedAt:new Date().toISOString()});if(evidence.length>900000){setError('Evidence exceeds this synthetic journal limit. Use a smaller extract.');return;}onUseSource?.({name:source.name,hash:source.hash,rows:source.releaseRows,evidence});setNotice('Source loaded. Run laboratory quality checks and review a new package.');}
 return <section className="dc-panel"><span className="dc-eyebrow"><FileSearch size={16}/> SOURCE REVIEW · LOCAL PROCESSING</span><h2>Every extracted field has a place to return to.</h2><p>Open a synthetic file. Structured fields are parsed directly; narrative content uses local AI. Select a result to see its source location. AI annotations stay separate from original records.</p>
 <label className="dc-check"><input type="checkbox" checked={synthetic} disabled={busy} onChange={e=>setSynthetic(e.target.checked)}/>I am using synthetic demonstration files, not patient information.</label>
 <DoclingSetup disabled={busy} onReady={setDoclingReady}/><label className="dc-check"><input type="checkbox" checked={advanced} disabled={busy||!isTauri} onChange={e=>setAdvanced(e.target.checked)}/>Use advanced PDF layout and OCR (Docling). Uncheck to use the basic text reader.</label>
 <div className="dc-actions"><input ref={input} type="file" hidden accept=".pdf,.docx,.txt,.md,.markdown,.csv,.tsv,.xlsx,.json,.ndjson,.hl7" onChange={e=>{const f=e.target.files?.[0];if(f&&synthetic)void load(f);e.target.value='';}}/><button className="dc-btn primary" disabled={!synthetic||busy} onClick={()=>input.current?.click()}><Upload size={15}/>Open synthetic file</button><button className="dc-btn" disabled={busy} onClick={()=>{setSynthetic(true);void load(new File([NOTE],'synthetic-lab-note.txt',{type:'text/plain'}));}}>Load example note</button>{source?.mode==='narrative'&&<button className="dc-btn primary" disabled={busy||!isTauri||!synthetic} onClick={()=>void extract()}>Extract with local model <ArrowRight size={14}/></button>}{busy&&<button className="dc-btn" onClick={()=>void cancel()}>Cancel processing</button>}</div>
 <p className="mt-3">Text PDF, DOCX, TXT/Markdown · CSV/TSV, XLSX · FHIR JSON/NDJSON · HL7 files. Up to 12 MB and 30 PDF pages. Scanned PDFs require the advanced reader. Other image formats are not yet enabled.</p>
 {!isTauri&&<p className="mt-2">Browser: source parsing and evidence review work; live model extraction requires the desktop app.</p>}
 {error&&<p role="alert" className="dc-error">{error}</p>}{notice&&<p role="status" className="dc-notice mt-3">{notice}</p>}
 {source&&<><div className="dc-file-summary"><div><strong>{source.name}</strong><p>{source.format.toUpperCase()} · {source.segments.length} source locations · {entities.length} fields / entities</p></div><span>{source.mode==='structured'?'Deterministic parser':'Local model required'}</span></div><p role="status">{status}{busy?` · ${seconds}s elapsed`:''}</p>{metrics.length>0&&<p className="mt-2">{metrics[0]!.model} · {(metrics.reduce((n,m)=>n+m.latency_ms,0)/1000).toFixed(1)}s across {metrics.length} section(s) · {supported.length}/{entities.length} exact-source matches. Matching text does not prove clinical interpretation.</p>}{source.documentReader&&<div className="dc-source-warning"><strong>Docling · {source.documentReader.ocr} · {source.documentReader.elapsedSeconds.toFixed(1)}s</strong><p>{source.documentReader.verification}</p><p>Locations identify document blocks or table regions. Extracted text, OCR and header associations need visual review against the original page.</p></div>}{source.warnings.map((w,i)=><p className="dc-source-warning" key={i}>{w}</p>)}
 <div className="dc-evidence-workspace"><div><label htmlFor="entity-search">Find a field or entity</label><input id="entity-search" className="dc-input mt-2" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Test, value, field name or context…"/><div className="dc-entity-list">{visible.slice(0,150).map(e=><article key={e.id} className={selected===e.id?'selected':''}><button className="dc-entity-target" onClick={()=>setSelected(e.id)}><small>{e.kind} · {e.assertion}</small><strong>{e.label}</strong><span>{e.value}{e.unit?` ${e.unit}`:''}</span><small>{e.supported?'View source location →':e.problem}</small></button>{e.origin==='model'&&<><label className="dc-check"><input type="checkbox" disabled={!e.supported||!complete||!coverage||rejected.includes(e.id)} checked={reviewed.includes(e.id)} onChange={event=>setReviewed(r=>event.target.checked?[...r,e.id]:r.filter(id=>id!==e.id))}/>I reviewed this entity and its context.</label><button className="dc-btn" disabled={!complete||busy} onClick={()=>{setReviewed(r=>r.filter(id=>id!==e.id));setRejected(r=>r.includes(e.id)?r.filter(id=>id!==e.id):[...r,e.id]);}}>{rejected.includes(e.id)?'Rejected · undo':'Reject suggestion'}</button></>}</article>)}{visible.length>150&&<p>Showing 150 of {visible.length}. Narrow the search to inspect another field.</p>}{!entities.length&&<div className="dc-empty"><FileSearch size={28}/><h3>{complete?'No entities returned':'Source ready for review'}</h3><p>{complete?'No facts were returned. This does not prove that the document contains no relevant facts.':'Run extraction to see candidate entities and click-through evidence.'}</p></div>}</div>{source.mode==='structured'&&<label className="dc-check"><input type="checkbox" checked={parsedReviewed} disabled={!complete||!coverage} onChange={e=>setParsedReviewed(e.target.checked)}/>I reviewed the parsed source fields and file coverage.</label>}</div>
 <div className="dc-source-viewer" ref={sourcePane} aria-label="Original source viewer" tabIndex={0}>{segment&&<><div className="dc-source-heading"><label htmlFor="source-location">Source location</label><select id="source-location" className="dc-input mt-2 mb-3" value={segment.id} onChange={e=>{setSelected('');setManualSegment(e.target.value);}}>{source.segments.map(s=><option key={s.id} value={s.id}>{s.label}</option>)}</select><strong>{segment.label}</strong><p>{source.name} · original source location</p></div>{segment.image?<div className="dc-pdf-page"><img src={segment.image} alt={`Original ${segment.label}`}/>{(active?.supported||(!active&&source.documentReader))&&segment.runs?.filter(r=>!active||(r.end>active.start&&r.start<active.end)).map((r,i)=><span key={i} className="dc-pdf-highlight" style={{left:`${r.box.x/segment.pageWidth!*100}%`,top:`${r.box.y/segment.pageHeight!*100}%`,width:`${r.box.width/segment.pageWidth!*100}%`,height:`${r.box.height/segment.pageHeight!*100}%`}}/>)}</div>:<pre>{active?.supported?<>{segment.text.slice(0,active.start)}<mark>{segment.text.slice(active.start,active.end)}</mark>{segment.text.slice(active.end)}</>:segment.text}</pre>}{active&&<div className="dc-source-context"><h3>Evidence and context</h3><p>{active.quote}</p><p className="mt-2">{active.subject?`Source subject: ${active.subject}`:'Patient association is not established by this annotation.'}</p>{active.origin==='model'&&<p className="mt-2">Assertion: {active.assertion}. Review negation, timing and attribution in the original source before accepting.</p>}</div>}</>}</div></div>
 <div className="dc-actions mt-4"><button className="dc-btn primary" disabled={!canExport} onClick={()=>void exportReview()}><Download size={15}/>Export reviewed evidence</button>{source.releaseRows&&onUseSource&&<button className="dc-btn" disabled={!canExport||pendingReceipt} onClick={useSource}>Use as laboratory source <ArrowRight size={14}/></button>}</div>{!coverage&&<p className="dc-source-warning">File coverage is incomplete or ambiguous. Reviewed export is blocked; use a complete text source.</p>}{source.releaseProblem&&<p className="mt-3">Laboratory release: {source.releaseProblem}</p>}{pendingReceipt&&<p className="mt-3">Reconcile the pending receipt before changing the laboratory source.</p>}
 <details className="mt-4"><summary>Extraction settings and traceability</summary><p>SHA-256: {source.hash}</p><p>Profile {profile.version}: JSON Schema enforced by Ollama; temperature 0; reasoning enabled; 8,192-token context; 4,096-token output cap; sequential bounded sections; 180 seconds per attempt with at most one source-grounding repair. Truncated or invalid responses fail closed.</p><p>Evidence remains in memory until exported or loaded into the synthetic journal. Original file hash, segment locations and annotation origin accompany the review. This is not approved de-identification, hospital authorization or clinical validation.</p></details></>}
 </section>;
}
